from sqlalchemy.dialects.mysql import TINYINT, SMALLINT, INTEGER, VARCHAR, TEXT, DATETIME, DATE
from application.services import db

class User(db.Model):
    __tablename__ = "users"

    userID          = db.Column(INTEGER(unsigned=True), nullable=False, primary_key=True) 
    userTypeID      = db.Column(TINYINT(unsigned=True), db.ForeignKey('user_types.userTypeID'), nullable=False) 
    nstpComponentID = db.Column(TINYINT(unsigned=True), db.ForeignKey('nstp_components.nstpComponentID'), nullable=False) 
    courseID        = db.Column(TINYINT(unsigned=True), db.ForeignKey('courses.courseID'), nullable=False) 
    yearLevel       = db.Column(TINYINT, nullable=False) 
    studentNo       = db.Column(VARCHAR(20), nullable=False) 
    username        = db.Column(VARCHAR(150), nullable=False) 
    password        = db.Column(VARCHAR(60), nullable=False) 
    lname           = db.Column(VARCHAR(30), nullable=False) 
    fname           = db.Column(VARCHAR(30), nullable=False) 
    mname           = db.Column(VARCHAR(30), nullable=False) 
    ename           = db.Column(VARCHAR(10), nullable=False) 
    gender          = db.Column(TINYINT, nullable=False) 
    birthDate       = db.Column(DATE, nullable=True) 
    birthPlace      = db.Column(TEXT, nullable=False) 
    religion        = db.Column(VARCHAR(20), nullable=False) 
    citizenship     = db.Column(VARCHAR(20), nullable=False) 
    phone           = db.Column(VARCHAR(11), nullable=False) 
    email           = db.Column(TEXT, nullable=False) 
    addressHomeStreet               = db.Column(VARCHAR(100), nullable=False) 
    addressHomeMunicipality         = db.Column(VARCHAR(50), nullable=False) 
    addressHomeProvince             = db.Column(VARCHAR(50), nullable=False) 
    addressHomePhone                = db.Column(VARCHAR(11), nullable=False) 
    addressTemporaryStreet          = db.Column(VARCHAR(100), nullable=False) 
    addressTemporaryMunicipality    = db.Column(VARCHAR(50), nullable=False) 
    addressTemporaryProvince        = db.Column(VARCHAR(50), nullable=False) 
    addressTemporaryPhone           = db.Column(VARCHAR(11), nullable=False) 
    fatherName                      = db.Column(VARCHAR(90), nullable=False) 
    fatherOccupation                = db.Column(VARCHAR(20), nullable=False) 
    motherName                      = db.Column(VARCHAR(90), nullable=False) 
    motherOccupation                = db.Column(VARCHAR(20), nullable=False) 
    emergencyContactName            = db.Column(VARCHAR(90), nullable=False) 
    emergencyContactPhone           = db.Column(VARCHAR(11), nullable=False) 
    emergencyContactRelationship    = db.Column(VARCHAR(20), nullable=False) 
    emergencyContactAddress         = db.Column(TEXT, nullable=False) 
    height          = db.Column(VARCHAR(10), nullable=False) 
    weigh           = db.Column(VARCHAR(10), nullable=False) 
    complexion      = db.Column(TEXT, nullable=False) 
    bloodTypeID     = db.Column(TINYINT, db.ForeignKey('blood_types.bloodTypeID'), nullable=False) 
    takeAdvanceCourse = db.Column(TINYINT, nullable=False) 
    picExt          = db.Column(VARCHAR(5), nullable=False) 
    status          = db.Column(TINYINT, nullable=False) 